### ISSUE TITLE
Unit 8 Sprint Plan

### ISSUE THREAD

**Issue by VincentCarrancho** [ChaRizzMa/RizzTracker#1]
# TODOs this sprint (Unit 8)
- [ ] Finalize the Figma Prototype @VincentCarrancho 
- [x] Work on login and create account flow @VincentCarrancho 
- [x] #6
- [x] Finalize user struct @quigongian @tehniel 
- [x] Create database @quigongian @tehniel 
- [ ] Create algorithm for the rizz calculation @mweet003 @VincentCarrancho 
- [ ] Create My Rizz page and discuss what needs to be implemented. @SayfTanbir 

## Extra Notes
- User struct must contain a variable named `friends` in which it is an array of user ID's representing the user's friends (not to be confused with username).
- Researching on how to implement line graphs on the user's rizz on the My Rizz page @SayfTanbir.
- Polishing wireframes @nicholas-deSouza
