### ISSUE TITLE
Unit 9 Sprint Plan

### ISSUE THREAD

**Issue by VincentCarrancho** [ChaRizzMa/RizzTracker#3]
# Tasks

- [ ] Interface with database on each member's parts
    - [ ] Read/Write operations on Home Page @quigongian @tehniel 
    - [ ] Write operations on Add Rizz page @mweet003 
    - [ ] Read operations on My Rizz page @SayfTanbir 
- [ ] Finalize Figma prototype so @SayfTanbir can start development on that @nicholas-deSouza 
- [ ] Create algorithm for both the Add Rizz page and initial rizz (on User Sign-up) @mweet003 @VincentCarrancho 
- [ ] Create script that creates data (presentation purposes)
    - Must be able to create users and accompanying rizz reports.

## Notes

Progress going well, we were just hampered by exams this week.
